version: "3.9"
services:
  spring:
    build:
      context: .
    environment:
      PSQL_HOST: "db"
      PSQL_USERNAME: "postgres"
      PSQL_PASSWORD: "password"
    networks:
      - backend
    ports:
      - "8089:8080"

  db:
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "B-Fit"
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"

networks:
  backend:

volumes:
  db-data: